services:

  serveur_symfony:
    container_name: serveur_symfony
    image: nginx:1.31.1-alpine3.23
    working_dir: /www
    volumes:
      - './symfony:/www/symfony'
      - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro'

  php:
    container_name: php
    build: ./docker/php
    working_dir: /www/symfony
    volumes:
      - './symfony/:/www/symfony'

  postgres:
    container_name: postgres
    image: postgres:18-alpine3.24
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - symfony_data:/var/lib/postgresql/18/docker

volumes:
  symfony_data: