name: ci
on:
  pull_request:
    branches:
      - dev

jobs:
  build-test-symfony:
    runs-on: ubuntu-latest
    steps:
      - name: Install checkout
        uses: actions/checkout@v7

      - name: Build Docker services
        run: docker compose -f compose.yml build

      - name: docker up && install dependencies
        run: |
          docker compose run --rm php_composer composer install \
          --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Run tests
        run: docker compose run --rm php_composer vendor/bin/phpunit

      - name: Stop Docker and clean container
        if: always()
        run: docker compose down
